image:
#  - Visual Studio 2015
  - Ubuntu

#environment:
#  matrix:
#    - TOXENV: py34-mywin32
#      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
#    - TOXENV: py34-mywin64
#      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
#    - TOXENV: py35-mywin32
#      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
#    - TOXENV: py35-mywin64
#      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
#    - TOXENV: py36-mywin32
#      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
#    - TOXENV: py36-mywin64
#      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
#    - TOXENV: py37-mywin32
#      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
#    - TOXENV: py37-mywin64
#      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
#    - TOXENV: py38-mywin32
#      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
#    - TOXENV: py38-mywin64
#      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

build: off

install:
  - cmd: set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - cmd: python -VV
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -m pip install --upgrade pip setuptools
  - cmd: pip install tox
  - sh: python3 -VV
  - sh: python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - sh: pip install tox
  - sh: PATH=/home/appveyor/.local/bin:${PATH}

test_script:
  - cmd: python -m tox
  - sh: tox
