image:
  - Visual Studio 2015
  - Ubuntu1804
  - macOS

platform:
  - x86
  - x64

environment:
  matrix:
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

build: off

install:
  - py -3.8 -m pip install --upgrade pip setuptools
  - py -3.8 -m pip install tox

test_script:
  - py -3.8 -m tox
