image:
  - Ubuntu1804
  - Visual Studio 2015
  - macOS

platform:
  - x86
  - x64

environment:
  matrix:
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

for:
  - matrix:
      only:
        - image: Visual Studio 2015
        - platform: x86
    environment:
      PATH: C:\Python38;C:\Python38\Scripts;%PATH%
      PYTHON: python
      PIP: pip
  - matrix:
      only:
        - image: Visual Studio 2015
        - platform: x64
    environment:
      PATH: C:\Python38_64;C:Python38_64\Scripts;%PATH%
      PYTHON: python
      PIP: pip
  - matrix:
      except:
        - image: Visual Studio 2015
    environment:
      PYTHON: python3
      PIP: pip3

build: off

install:
  - %PYTHON% -m pip install --upgrade pip setuptools
  - %PIP% install tox

test_script:
  - tox
