environment:
  matrix:
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

build: off

install:
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m pip install --upgrade pip setuptools
  - pip install tox

test_script:
  - tox