image:
  - Visual Studio 2015
  - Ubuntu


environment:
  matrix:
    - TOXENV: py35
      PYTHON_VERSION: 3.5
    - TOXENV: py36
      PYTHON_VERSION: 3.6
    - TOXENV: py37
      PYTHON_VERSION: 3.7
    - TOXENV: py38
      PYTHON_VERSION: 3.8

stack: python %PYTHON_VERSION%

build: off

install:
  - cmd: set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - cmd: python -VV
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -m pip install --upgrade pip setuptools
  - cmd: pip install tox
  - sh: python -VV
  - sh: python -c "import struct; print(struct.calcsize('P') * 8)"
  - sh: pip install tox
  - sh: PATH=/home/appveyor/.local/bin:${PATH}

test_script:
  - cmd: python -m tox
  - sh: tox
